### ISSUE TITLE
ArchLingmo 0.1 TODOs

### ISSUE THREAD

**Issue by chun-awa** [LingmoOS-Testing/lingmo-archiso-build#3]
- [x] Update packages (moved to <https://github.com/LingmoOS/archlingmo-pkg>)
- [x] Reduce ISO image size (1.87GB in https://github.com/LingmoOS/archlingmo-archiso-config/actions/runs/10178420885)
- [x] ~~Add nvidia closed-source drivers~~ not planned anymore
- [x] Add installer
- [x] Add more utils
- [x] Update bootloader config
- [x] Fix icons not working (related to qt-plugins)
- [x] Add kwin-plugins again

**Comment by lldxlzy** [comment]
我，，，尼玛
